# Generated by Django 4.1.1 on 2022-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=600, verbose_name='ISM FAMILIYA')),
                ('phone', models.CharField(max_length=600, verbose_name='TELEFON')),
                ('message', models.TextField(verbose_name='XABAR')),
                ('ip', models.CharField(max_length=400, verbose_name='IP ADDRESS')),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aloqa Bo`limi',
                'verbose_name_plural': 'Aloqa Bo`limi',
            },
        ),
    ]
