# Generated by Django 4.1.1 on 2022-09-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Site Logo', 'verbose_name_plural': 'Site Logo'},
        ),
    ]
