# Generated by Django 4.1.1 on 2022-09-24 20:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_logo_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=600)),
                ('category', models.CharField(max_length=600)),
                ('phone', models.CharField(max_length=600)),
                ('about_me', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
