# Generated by Django 4.1.1 on 2022-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Ustozlar', 'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='nimadur', upload_to='images/teacher/'),
            preserve_default=False,
        ),
    ]
