# Generated by Django 4.1.1 on 2022-09-24 21:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_teacher_options_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='images/courses/')),
                ('about', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Kurslar',
                'verbose_name_plural': 'Kurslar',
            },
        ),
    ]
