# Generated by Django 4.1.1 on 2022-09-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.teacher'),
            preserve_default=False,
        ),
    ]
