# Generated by Django 4.1.1 on 2022-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
