# Generated by Django 4.1.1 on 2022-09-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycourses', to='home.course')),
            ],
        ),
    ]
