# Generated by Django 4.1.1 on 2022-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_result_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=600)),
                ('full_name', models.CharField(max_length=600)),
                ('phone', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=200)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs uchun qabul',
                'verbose_name_plural': 'Kurs uchun qabul',
            },
        ),
    ]
