# Generated by Django 4.1.1 on 2022-09-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_enrollcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollcourse',
            options={'verbose_name': 'Kurs Uchun Qabul', 'verbose_name_plural': 'Kurs Uchun Qabul'},
        ),
    ]
