# Generated by Django 4.1.1 on 2022-09-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homescreen',
            options={'verbose_name': 'Home Screen', 'verbose_name_plural': 'Home Screen'},
        ),
    ]
