# Generated by Django 4.1.1 on 2022-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_botandchatidcontact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotAndChatId2Course',
            new_name='BotAndChatIdCourse',
        ),
    ]
