# Generated by Django 4.1.1 on 2022-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_rename_botandchatid2course_botandchatidcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='mn', upload_to='images/site_settings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homescreen',
            name='image',
            field=models.ImageField(default='nm', upload_to='images/site_settings/'),
            preserve_default=False,
        ),
    ]
